# Generated by Django 4.0.4 on 2022-05-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jstagram', '0002_rename_loation_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='jstagram/post/%Y/%m/%d'),
        ),
    ]
