# Generated by Django 4.0.4 on 2022-05-20 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jstagram', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
    ]
