# Generated by Django 4.0.4 on 2022-05-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_profile_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='48px * 48px png or jpg needed', upload_to='accounts/avatar/%Y/%m/%d'),
        ),
    ]
